version: '1'
services:
  mysql_demo:
    image: mysql
    restart: always
    ports:
      - "3306:3306"
    volumes:
      - ./mysql/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    environment:
      MYSQL_ROOT_PASSWORD: root
    networks:
      - education-net

  mongodb:
    image: mongo:latest
    restart: unless-stopped
    volumes:
      - ./mongodb/initdb.d/mongo-init.js:/docker-entrypoint-initdb.d/mongo/mongo-init.js:ro
    ports:
      - "27017:27017"
    networks:
      - education-net




  keycloak_demo:
    image: quay.io/keycloak/keycloak:latest
    restart: unless-stopped
    command: [ "start-dev" ]
    environment:
      KC_DB: mysql
      KC_DB_URL: jdbc:mysql://mysql_demo:3306/keycloak_demo
      KC_DB_USERNAME: admin01
      KC_DB_PASSWORD: H1f78tnajhg&*
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_HOSTNAME_STRICT: false
      KC_HOSTNAME_STRICT_HTTPS: false
      KC_PROXY: edge
      KEYCLOAK_FRONTEND_URL: http://keycloak_demo:8080  # Fixed
    ports:
      - "7070:8080"
    depends_on:
      - mysql_demo
    networks:
      - education-net


  register-service:
    build:
      context: ./service-registry
    restart: unless-stopped
    ports:
      - "8761:8761"
    networks:
      - education-net

  school-service:
    depends_on:
      - mysql_demo
      - keycloak_demo
    build:
      context: ./school-service
    restart: always
    ports:
      - "9090:9090"
    environment:
      DB_URL: jdbc:mysql://mysql_demo:3306/school
      DB_USER: admin01
      DB_PASSWORD: H1f78tnajhg&*
    networks:
      - education-net

  student-service:
    depends_on:
      - mongodb
      - keycloak_demo
    build:
      context: ./student-service
    restart: always
    ports:
      - "9091:9091"
    environment:
      DB_URL: mongodb://mongodb:27017/student-service
#      DB_USER: admin01
#      DB_PASSWORD: H1f78tnajhg&*
    networks:
      - education-net

  api-gateway:
    build:
      context: ./cloud-gateway
    restart: unless-stopped
    ports:
      - "9191:9191"
    networks:
      - education-net

networks:
  education-net:

