spring:
  main:
    allow-bean-definition-overriding: true
  application:
    name: STUDENT-SERVICE
  data:
    mongodb:
      uri: mongodb://mongodb:27017/student-service
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://keycloak_demo:8080/realms/Miscro-services/protocol/openid-connect/certs
      client:
        provider:
          keycloak:
            issuer-uri: http://keycloak_demo:8080/realms/Miscro-services


server:
  port: 9091

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://register-service:8761/eureka/
  instance:
    hostname: student-service

management:
  endpoint:
    health:
      show-details: always
  health:
    circuitbreakers:
      enabled: true
  web:
    exposure:
      include: health,info

resilience4j:
  circuitbreaker:
    instances:
      student-service:
        registerHealthIndicator: true
        failureRateThreshold: 50
        minimumNumberOfCalls: 5
        automaticTransitionFromOpenToHalfOpenEnabled: true
        waitDurationInOpenState: 10s
        permittedNumberOfCallsInHalfOpenState: 3
        slidingWindowSize: 10
        slidingWindowType: COUNT_BASED
