CREATE DATABASE IF NOT EXISTS keycloak_demo;
CREATE DATABASE IF NOT EXISTS school;

CREATE USER IF NOT EXISTS 'admin01'@'%' IDENTIFIED BY 'H1f78tnajhg&*';
GRANT ALL PRIVILEGES ON keycloak_demo.* TO 'admin01'@'%';
GRANT ALL PRIVILEGES ON school.* TO 'admin01'@'%';

FLUSH PRIVILEGES

